Truncate decimal for credit card refunds
xendit/xendit-magento-payment-module pull request #116
Opened 2022-02-17 08:44 UTC by andykim

## Description

Truncate decimal for credit card refunds

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Cosmetic change (text changing or color changing)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code (if necessary), particularly in hard-to-understand areas
- [ ] My changes generate no new vulnerabilities
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshot

`put screenshot here if there are any ui changes`

2022-02-17 09:00 UTC, rendegosling commented on Xendit/M2Invoice/Model/Payment/CC.php
> +                'amount' => $this->getCurrency() == 'IDR' ? ceil($amount) : $amount,
`ceil($amount)` work?

2022-02-17 09:03 UTC, andykim commented on Xendit/M2Invoice/Model/Payment/CC.php
> +                'amount' => $this->getCurrency() == 'IDR' ? ceil($amount) : $amount,
@rendegosling it will round up number to the next highest integer.
ex: 
`
echo ceil(4.3);    // 5
echo ceil(9.999);  // 10
`

2022-02-17 09:20 UTC, rendegosling commented on Xendit/M2Invoice/Model/Payment/CC.php
> +                'amount' => $this->getCurrency() == 'IDR' ? ceil($amount) : $amount,
AFAIK the requirement involves truncating not rounding. I opened a thread in #_tpi @andykim

2022-02-17 09:20 UTC, rendegosling requested changes
we dont need to round

2022-02-17 09:26 UTC, rendegosling commented
@andykim is it to add phpunit in this repo so we can start creating unit tests for things like this?

2022-02-17 10:16 UTC, andykim commented on Xendit/M2Invoice/Model/Payment/CC.php
> +                'amount' => $this->getCurrency() == 'IDR' ? ceil($amount) : $amount,
Hi @rendegosling 

I change the function to truncate decimal and add the unit tests. Please check it.

![Screenshot from 2022-02-17 17-15-48](https://user-images.githubusercontent.com/5335952/154455045-111db892-cf68-459f-9108-e983a30fd495.png)

![Screenshot from 2022-02-17 17-14-43](https://user-images.githubusercontent.com/5335952/154454963-ce58a133-f57c-4845-898c-5c2d54629876.png)

2022-02-17 10:17 UTC, rendegosling commented on Xendit/M2Invoice/Test/Unit/Helper/TruncateDecimalTest.php
> +        $this->assertEquals($this->_dataHelper->truncateDecimal(100000.99), 100000);
should we allow negative numbers?

2022-02-17 10:24 UTC, andykim commented on Xendit/M2Invoice/Test/Unit/Helper/TruncateDecimalTest.php
> +        $this->assertEquals($this->_dataHelper->truncateDecimal(100000.99), 100000);
> should we allow negative numbers?

Hi @rendegosling . Do you mean add the case with negative numbers in the unit tests?

2022-02-17 10:24 UTC, rendegosling commented on Xendit/M2Invoice/Helper/Data.php
> +        return floor((float)$amount);
I got slight concern on casting float, is there a `decimal` type in PHP that we can use? @andykim

2022-02-17 10:25 UTC, rendegosling commented on Xendit/M2Invoice/Helper/Data.php
> +        return floor((float)$amount);
base on my experience I avoid using float on anything monetary values https://husobee.github.io/money/float/2016/09/23/never-use-floats-for-currency.html

2022-02-17 10:27 UTC, rendegosling commented on Xendit/M2Invoice/Model/Payment/CC.php
> +                'amount' => $this->getCurrency() == 'IDR' ? ceil($amount) : $amount,
thanks for adding PHPunit

2022-02-17 10:31 UTC, andykim commented on Xendit/M2Invoice/Helper/Data.php
> +        return floor((float)$amount);
Actually I think using double will be exact than float.

2022-02-17 10:32 UTC, rendegosling commented on Xendit/M2Invoice/Helper/Data.php
> +        return floor((float)$amount);
if it's the same let's just use `double` for casting then. I just want to retain no usage of float with dealing with money matter 👍

2022-02-17 10:35 UTC, andykim commented on Xendit/M2Invoice/Helper/Data.php
> +        return floor((float)$amount);
@rendegosling You're right. I changed to `double`

2022-02-17 11:11 UTC, rendegosling approved these changes

2022-02-17 20:45 UTC, candrasaputra approved these changes
cool.
we have unit test on plugin now.
thanks @andykim

2022-02-18 01:52 UTC, andykim commented
> @andykim is it easy to add phpunit in this repo so we can start creating unit tests for things like this?

Hi @rendegosling . That's the code standard of the Magento extension. It already has the phpunit so next time we can add the unit tests like this in our extension. I think it's similar to the unit testing on nodejs/typescript

2022-02-18 02:03 UTC, merged